import { CSSProperties } from 'react';

const styles: Record<string, CSSProperties> = {
  container: {
    width: '100%',
    maxWidth: '1200px',
    margin: '40px auto',
    padding: '0 20px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  title: {
    fontSize: '28px',
    fontWeight: 'bold',
    margin: '0',
    color: '#333',
  },
  countdown: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  countdownItem: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#333',
  },
  countdownSeparator: {
    fontSize: '14px',
    color: '#333',
  },
  controls: {
    display: 'flex',
    gap: '10px',
  },
  controlButton: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: 'rgb(118, 150, 62)',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  productsContainer: {
    display: 'flex',
    gap: '20px',
    flexWrap: 'wrap',
  },
  bestSeller: {
    flex: '1 1 250px',
    minHeight: '300px',
    borderRadius: '8px',
    overflow: 'hidden',
    position: 'relative',
    backgroundImage: 'url(https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2000&q=80)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  bestSellerContent: {
    padding: '20px',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: '8px 8px 0 0',
  },
  bestSellerTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    margin: '0 0 5px 0',
    color: '#333',
  },
  bestSellerSubtitle: {
    fontSize: '16px',
    margin: '0 0 15px 0',
    color: '#666',
  },
  bestSellerPrice: {
    position: 'relative',
    display: 'inline-block',
  },
  priceTag: {
    display: 'block',
    backgroundColor: '#e6c619',
    color: 'white',
    padding: '5px 10px',
    borderRadius: '15px 15px 0 15px',
    fontSize: '14px',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  price: {
    display: 'block',
    backgroundColor: '#e6c619',
    color: 'white',
    padding: '5px 10px',
    borderRadius: '0 0 15px 15px',
    fontSize: '22px',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  productCard: {
    flex: '1 1 250px',
    borderRadius: '8px',
    overflow: 'hidden',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    backgroundColor: 'white',
    transition: 'transform 0.3s ease',
  },
  productLink: {
    textDecoration: 'none',
    color: 'inherit',
    display: 'block',
  },
  productImage: {
    width: '100%',
    height: '200px',
    objectFit: 'cover',
    borderBottom: '1px solid #eee',
  },
  productInfo: {
    padding: '15px',
  },
  productName: {
    fontSize: '16px',
    fontWeight: 'bold',
    margin: '0 0 10px 0',
    color: '#333',
    textAlign: 'center',
  },
  productPrice: {
    fontSize: '18px',
    color: '#666',
    margin: '0 0 10px 0',
    textAlign: 'center',
  },
  productRating: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '2px',
  },
};

export default styles;
