export const styles = {
  hero: {
    backgroundImage: "url('/bio_market.png')",
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    padding: '80px 20px',
    textAlign: 'center',
    color: 'white',
    borderRadius: '12px',
    maxWidth: '1200px', 
    minHeight: '600px',
    margin: '20px auto 0px',
    position: 'relative',
  },
  title: {
    fontSize: '48px',
    marginBottom: '20px',
  },
  subtitle: {
    fontSize: '24px',
    marginBottom: '40px',
  },
  shopButton: {
    backgroundColor: 'rgb(118, 150, 62)',
    color: 'white',
    padding: '12px 24px',
    borderRadius: '30px',
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: 'bold',
    display: 'inline-block',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    position: 'absolute',
    bottom: '20px', 
    left: '50%', 
    transform: 'translateX(-50%)', 
    ':hover': {
      backgroundColor: '#2f5a6e',
      transform: 'translateX(-50%) translateY(-3px)',
      boxShadow: '0 6px 12px rgba(0, 0, 0, 0.15)',
    },
  },
};